#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'lcsd.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'lcsd.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'lcsd.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'lcsd.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'lcsd.service' >/dev/null || true
fi
# End automatically added section
