[cluster]
name = demo
node = c

[node a]
role = full-member
address = 192.168.0.1

[node b]
role = full-member
address = 192.168.0.2

[node c]
role = quorum-only
address = 192.168.0.3

[vip vip1]
address = 192.168.0.4/24
interface = eth0

